-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SUPABASE SQL EDITOR NAME: 001_create_tables
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- ╔══════════════════════════════════════════════════════════════╗
-- ║  AttendX — ESSL K30 Pro Attendance Dashboard                ║
-- ║  Migration 001: Create all tables                           ║
-- ║  Run this in Supabase SQL Editor (new project)              ║
-- ╚══════════════════════════════════════════════════════════════╝

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ─── 1. DEVICES ─────────────────────────────────────────────────
CREATE TABLE public.devices (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(100) NOT NULL,
  ip_address    VARCHAR(45)  NOT NULL,
  port          INTEGER      NOT NULL DEFAULT 4370,
  comm_key      INTEGER      DEFAULT 0,
  machine_id    INTEGER      DEFAULT 1,
  model_name    VARCHAR(50)  DEFAULT 'K30 Pro',
  serial_number VARCHAR(100),
  firmware      VARCHAR(100),
  mac_address   VARCHAR(50),
  is_active     BOOLEAN      DEFAULT TRUE,
  status        VARCHAR(20)  DEFAULT 'disconnected',  -- connected | disconnected | error
  last_seen     TIMESTAMPTZ,
  last_sync     TIMESTAMPTZ,
  created_at    TIMESTAMPTZ  DEFAULT NOW()
);

-- ─── 2. EMPLOYEES ───────────────────────────────────────────────
CREATE TABLE public.employees (
  enroll_number   BIGINT PRIMARY KEY,
  name            VARCHAR(200) NOT NULL,
  department      VARCHAR(100),
  designation     TEXT,
  privilege       INTEGER      DEFAULT 0,  -- 0=user, 14=admin
  card_number     VARCHAR(50)  DEFAULT '0',
  password        VARCHAR(50)  DEFAULT '',
  mobile_number   VARCHAR(20),
  emergency_contact VARCHAR(20),
  email           TEXT,
  shift_start     TIME         DEFAULT '09:00:00',
  shift_end       TIME         DEFAULT '18:00:00',
  joining_date    DATE         DEFAULT CURRENT_DATE,
  is_active       BOOLEAN      DEFAULT TRUE,
  status          TEXT         DEFAULT 'Active',
  base_salary     BIGINT       DEFAULT 0,
  pan_number      VARCHAR(20),
  aadhaar_number  VARCHAR(20),
  uan_number      VARCHAR(30),
  leave_balance_cl INTEGER     DEFAULT 12,
  leave_balance_sl INTEGER     DEFAULT 6,
  sort_order      INTEGER      DEFAULT 100000,
  created_at      TIMESTAMPTZ  DEFAULT NOW(),
  updated_at      TIMESTAMPTZ  DEFAULT NOW()
);

-- ─── 3. RAW PUNCHES ────────────────────────────────────────────
CREATE TABLE public.raw_punches (
  id              BIGSERIAL PRIMARY KEY,
  enroll_number   BIGINT       NOT NULL REFERENCES public.employees(enroll_number) ON DELETE CASCADE,
  punch_time      TIMESTAMP    NOT NULL,
  device_id       BIGINT       REFERENCES public.devices(id) ON DELETE SET NULL,
  verify_mode     INTEGER      DEFAULT 0,
  synced_at       TIMESTAMPTZ  DEFAULT NOW()
);

-- Prevent duplicate punches
CREATE UNIQUE INDEX idx_raw_punches_unique
  ON public.raw_punches (enroll_number, punch_time, device_id);

-- Fast queries by date
CREATE INDEX idx_raw_punches_time ON public.raw_punches (punch_time);
CREATE INDEX idx_raw_punches_enroll ON public.raw_punches (enroll_number);

-- ─── 4. DAILY ATTENDANCE ───────────────────────────────────────
CREATE TABLE public.daily_attendance (
  id              SERIAL PRIMARY KEY,
  enroll_number   BIGINT       NOT NULL REFERENCES public.employees(enroll_number) ON DELETE CASCADE,
  work_date       DATE         NOT NULL,
  in_time         TIMESTAMP,
  out_time        TIMESTAMP,
  total_hours     DOUBLE PRECISION DEFAULT 0,
  status          TEXT,  -- Present | Absent | Half Day | Weekend | Holiday | Leave
  is_late         BOOLEAN      DEFAULT FALSE,
  late_by_mins    INTEGER      DEFAULT 0,
  is_overtime     BOOLEAN      DEFAULT FALSE,
  ot_hours        DOUBLE PRECISION DEFAULT 0,
  remarks         TEXT,
  computed_at     TIMESTAMPTZ  DEFAULT NOW(),
  UNIQUE(enroll_number, work_date)
);

CREATE INDEX idx_daily_att_date ON public.daily_attendance (work_date);
CREATE INDEX idx_daily_att_enroll ON public.daily_attendance (enroll_number);

-- ─── 5. ATTENDANCE RULES (Global Settings) ─────────────────────
CREATE TABLE public.attendance_rules (
  id                    SERIAL PRIMARY KEY,
  company_name          TEXT         DEFAULT 'My Company',
  shift_start           TIME         DEFAULT '09:00:00',
  shift_end             TIME         DEFAULT '18:00:00',
  grace_period_mins     INTEGER      DEFAULT 15,
  half_day_threshold_hrs DOUBLE PRECISION DEFAULT 4.5,
  overtime_trigger_mins INTEGER      DEFAULT 30,
  weekend_days          TEXT[]       DEFAULT ARRAY['Sunday'],
  created_at            TIMESTAMPTZ  DEFAULT NOW()
);

-- Seed default row
INSERT INTO public.attendance_rules (company_name) VALUES ('Quezex');

-- ─── 6. HOLIDAYS ───────────────────────────────────────────────
CREATE TABLE public.holidays (
  id            SERIAL PRIMARY KEY,
  holiday_date  DATE         NOT NULL UNIQUE,
  name          VARCHAR(200) NOT NULL,
  type          VARCHAR(20)  DEFAULT 'public'  -- public | optional
);

-- ─── 7. DEVICE COMMANDS (Dashboard → Agent → Machine) ──────────
CREATE TABLE public.device_commands (
  id            BIGSERIAL PRIMARY KEY,
  device_id     BIGINT       NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
  command_type  VARCHAR(50)  NOT NULL,
  -- command_type values:
  --   sync_attendance, sync_users, add_user, delete_user,
  --   sync_time, restart, clear_logs, get_info
  payload       JSONB        DEFAULT '{}',
  status        VARCHAR(20)  DEFAULT 'pending',  -- pending | processing | completed | failed
  result        TEXT,
  created_by    TEXT,
  created_at    TIMESTAMPTZ  DEFAULT NOW(),
  executed_at   TIMESTAMPTZ
);

CREATE INDEX idx_commands_pending ON public.device_commands (status) WHERE status = 'pending';

-- ─── 8. AGENT HEARTBEAT ────────────────────────────────────────
CREATE TABLE public.agent_heartbeat (
  id            SERIAL PRIMARY KEY,
  agent_id      VARCHAR(100) NOT NULL UNIQUE,
  last_ping     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  ip_address    VARCHAR(45),
  version       VARCHAR(20)  DEFAULT '1.0.0',
  status        VARCHAR(20)  DEFAULT 'online',
  machine_statuses JSONB     DEFAULT '{}',
  updated_at    TIMESTAMPTZ  DEFAULT NOW()
);

-- ─── 9. SYNC HISTORY ───────────────────────────────────────────
CREATE TABLE public.sync_history (
  id              BIGSERIAL PRIMARY KEY,
  device_id       BIGINT,
  device_name     VARCHAR(100),
  action          VARCHAR(50)  NOT NULL,
  records_count   INTEGER      DEFAULT 0,
  status          VARCHAR(20)  DEFAULT 'success',  -- success | error
  message         TEXT,
  created_at      TIMESTAMPTZ  DEFAULT NOW()
);

-- ─── 10. AUDIT LOG ─────────────────────────────────────────────
CREATE TABLE public.audit_log (
  id              BIGSERIAL PRIMARY KEY,
  user_email      TEXT,
  action          VARCHAR(100) NOT NULL,
  entity_type     VARCHAR(50),
  entity_id       TEXT,
  old_value       JSONB,
  new_value       JSONB,
  ip_address      VARCHAR(45),
  created_at      TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX idx_audit_log_time ON public.audit_log (created_at DESC);

-- ─── SEED: Insert the two K30 Pro machines ─────────────────────
INSERT INTO public.devices (name, ip_address, port, comm_key, machine_id, model_name)
VALUES
  ('Office',  '192.168.1.205', 4370, 1234, 1, 'ESSL K30 Pro'),
  ('Factory', '192.168.1.252', 4370, 1234, 2, 'ESSL K30 Pro');

COMMENT ON TABLE public.devices IS 'ESSL K30 Pro biometric attendance machines';
COMMENT ON TABLE public.raw_punches IS 'Raw punch data synced from machines — source of truth';
COMMENT ON TABLE public.daily_attendance IS 'Computed daily attendance summary per employee';
COMMENT ON TABLE public.device_commands IS 'Command queue: dashboard → agent → machine';
COMMENT ON TABLE public.agent_heartbeat IS 'Tracks whether the local sync agent is alive';
