-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- SUPABASE SQL EDITOR NAME: 001_Enterprise_ADMS_Schema
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Description: Completely rewritten schema for AttendX ADMS 
-- integration, focusing on row-level locks for queueing, 
-- soft-deletes, and cross-machine reconciliation.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ─── 1. DEVICES ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.devices (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(100) NOT NULL,
  ip_address    VARCHAR(45)  NOT NULL,
  port          INTEGER      NOT NULL DEFAULT 4370,
  comm_key      INTEGER      DEFAULT 0,
  machine_id    INTEGER      DEFAULT 1,
  model_name    VARCHAR(50)  DEFAULT 'ESSL K30 Pro',
  serial_number VARCHAR(100) UNIQUE,
  firmware      VARCHAR(100),
  mac_address   VARCHAR(50),
  is_active     BOOLEAN      DEFAULT TRUE,
  status        VARCHAR(20)  DEFAULT 'disconnected',  -- connected | disconnected | error
  last_seen     TIMESTAMPTZ,
  last_sync     TIMESTAMPTZ,
  created_at    TIMESTAMPTZ  DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  DEFAULT NOW()
);

-- ─── 2. EMPLOYEES (With Soft Delete & Primary Device) ──────────
CREATE TABLE IF NOT EXISTS public.employees (
  enroll_number     BIGINT PRIMARY KEY, -- Strictly enforced: NEVER reuse
  name              VARCHAR(200) NOT NULL,
  department        VARCHAR(100),
  designation       TEXT,
  privilege         INTEGER      DEFAULT 0,  -- 0=User, 14=Admin/Maintenance
  card_number       VARCHAR(50)  DEFAULT '0',
  password          VARCHAR(50)  DEFAULT '',
  primary_device_id BIGINT       REFERENCES public.devices(id) ON DELETE SET NULL, -- Enforces single-device attendance
  is_maintenance    BOOLEAN      DEFAULT FALSE, -- Used for filtering out of payroll
  is_deleted        BOOLEAN      DEFAULT FALSE, -- Soft delete flag
  deleted_at        TIMESTAMPTZ,                -- Archive timestamp
  created_at        TIMESTAMPTZ  DEFAULT NOW(),
  updated_at        TIMESTAMPTZ  DEFAULT NOW()
);

-- ─── 3. DEVICE USERS (Reconciliation Table) ────────────────────
-- Tracks exactly which user is physically synced to which device.
CREATE TABLE IF NOT EXISTS public.device_users (
  id            BIGSERIAL PRIMARY KEY,
  device_id     BIGINT NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
  enroll_number BIGINT NOT NULL REFERENCES public.employees(enroll_number) ON DELETE CASCADE,
  device_uid    BIGINT NOT NULL,
  name          TEXT,
  privilege     INTEGER DEFAULT 0,
  synced_at     TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (device_id, enroll_number)
);

-- ─── 4. BIOMETRICS ──────────────────────────────────────────────
-- Stores base64 templates. MUST be hard-deleted if user is soft-deleted.
CREATE TABLE IF NOT EXISTS public.biometrics (
  id            BIGSERIAL PRIMARY KEY,
  enroll_number BIGINT NOT NULL REFERENCES public.employees(enroll_number) ON DELETE CASCADE,
  finger_index  INTEGER NOT NULL, 
  template_type INTEGER NOT NULL DEFAULT 1, 
  template_data TEXT NOT NULL, 
  valid         INTEGER DEFAULT 1,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(enroll_number, finger_index)
);

CREATE INDEX idx_biometrics_enroll ON public.biometrics(enroll_number);

-- ─── 5. RAW PUNCHES ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.raw_punches (
  id            BIGSERIAL PRIMARY KEY,
  enroll_number BIGINT       NOT NULL REFERENCES public.employees(enroll_number) ON DELETE CASCADE,
  punch_time    TIMESTAMP    NOT NULL,
  device_id     BIGINT       REFERENCES public.devices(id) ON DELETE SET NULL,
  verify_mode   INTEGER      DEFAULT 0,
  is_manual     BOOLEAN      DEFAULT FALSE, -- True if frontend override applied
  is_deleted    BOOLEAN      DEFAULT FALSE,
  deleted_at    TIMESTAMPTZ,
  deleted_by    TEXT,
  delete_reason TEXT,
  synced_at     TIMESTAMPTZ  DEFAULT NOW(),
  UNIQUE (enroll_number, punch_time, device_id)
);

CREATE INDEX idx_raw_punches_time ON public.raw_punches (punch_time);

-- ─── 6. MESSAGE QUEUE (Fail-Safe Ingestion) ────────────────────
-- Replaces raw_cdata_payloads. Used by background workers with row-level locking.
CREATE TABLE IF NOT EXISTS public.message_queue (
  id            BIGSERIAL PRIMARY KEY,
  device_sn     VARCHAR(100) NOT NULL,
  table_name    VARCHAR(50)  NOT NULL,
  payload       TEXT         NOT NULL,
  priority      INTEGER      DEFAULT 10, -- 1=High (ATTLOG), 5=Med (Commands), 10=Low (Users/Bios)
  status        VARCHAR(20)  DEFAULT 'pending', -- pending | processing | completed | failed
  retry_count   INTEGER      DEFAULT 0,
  locked_at     TIMESTAMPTZ,
  locked_by     TEXT, -- e.g., worker PID or UUID
  error_message TEXT,
  created_at    TIMESTAMPTZ  DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  DEFAULT NOW()
);

-- Essential indices for fast queue polling
CREATE INDEX idx_queue_poll ON public.message_queue (status, priority ASC, created_at ASC) WHERE status IN ('pending', 'failed');
CREATE INDEX idx_queue_stale ON public.message_queue (status, locked_at) WHERE status = 'processing';

-- ─── 7. DEVICE COMMANDS ─────────────────────────────────────────
-- Queue for sending instructions *to* the devices (Restart, Delete, etc.)
CREATE TABLE IF NOT EXISTS public.device_commands (
  id            BIGSERIAL PRIMARY KEY,
  device_id     BIGINT       NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
  command_type  VARCHAR(50)  NOT NULL, -- sync_time, restart, add_user, delete_user
  payload       JSONB        DEFAULT '{}',
  status        VARCHAR(20)  DEFAULT 'pending', -- pending | processing | acknowledged | completed | failed
  result        TEXT,
  sync_metadata JSONB        DEFAULT '{}', -- Track parsing progress
  created_at    TIMESTAMPTZ  DEFAULT NOW(),
  executed_at   TIMESTAMPTZ
);

CREATE INDEX idx_commands_pending ON public.device_commands (device_id, status) WHERE status = 'pending';

-- ─── 8. TRIGGERS & FUNCTIONS ────────────────────────────────────

-- Function to auto-update 'updated_at' columns
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_employees_modtime BEFORE UPDATE ON public.employees FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
CREATE TRIGGER update_devices_modtime BEFORE UPDATE ON public.devices FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
CREATE TRIGGER update_queue_modtime BEFORE UPDATE ON public.message_queue FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

-- Function: Enforce Biometric Hard Deletion on Soft Delete
CREATE OR REPLACE FUNCTION enforce_biometric_hard_delete()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.is_deleted = TRUE AND OLD.is_deleted = FALSE THEN
        -- Permanently delete all biometric templates for this user to comply with privacy laws
        DELETE FROM public.biometrics WHERE enroll_number = NEW.enroll_number;
        -- Record timestamp
        NEW.deleted_at = NOW();
    END IF;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER enforce_biometric_privacy BEFORE UPDATE ON public.employees FOR EACH ROW EXECUTE PROCEDURE enforce_biometric_hard_delete();

-- ─── 9. ROW LEVEL SECURITY (RLS) ────────────────────────────────
-- (Enable as needed based on your Supabase client setup)
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.biometrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.raw_punches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_commands ENABLE ROW LEVEL SECURITY;

-- Default policies (allow all for service_role and authenticated dashboard users)
CREATE POLICY "Full access devices" ON public.devices FOR ALL USING (true);
CREATE POLICY "Full access employees" ON public.employees FOR ALL USING (true);
CREATE POLICY "Full access device_users" ON public.device_users FOR ALL USING (true);
CREATE POLICY "Full access biometrics" ON public.biometrics FOR ALL USING (true);
CREATE POLICY "Full access punches" ON public.raw_punches FOR ALL USING (true);
CREATE POLICY "Full access message_queue" ON public.message_queue FOR ALL USING (true);
CREATE POLICY "Full access device_commands" ON public.device_commands FOR ALL USING (true);
